return {
    -- 'nvim-lualine/lualine.nvim',
    -- lazy=false,
    -- dependencies = { 'nvim-tree/nvim-web-devicons'},
    --
    -- sections = {
    --     lualine_a = {'mode'},
    --     lualine_b = {'branch', 'diff', 'diagnostics'},
    --     lualine_c = {'filename'},
    --     lualine_x = {'encoding', 'fileformat', 'filetype'},
    --     lualine_y = {'progress'},
    --     lualine_z = {'location'}
    -- },
    --
    -- tabline = {
    --     lualine_a = {},
    --     lualine_b = {'branch'},
    --     lualine_c = {'filename'},
    --     lualine_x = {},
    --     lualine_y = {},
    --     lualine_z = {'tabs'}
    -- },
    --
    -- winbar = {},
}
